### ISSUE TITLE
Como rodar o projeto na vercel

### ISSUE THREAD

**Issue by alissonandrade2020** [isaiasnhantumbo/desafio-ignite-reactjs-interface-com-chakra-ui#1]
Bom dia Isaias.

tentei rodar o projeto aqui mas não foi será que fiz algo errado ??

**Comment by isaiasnhantumbo** [comment]
Boa noite @alissonandrade2020, é o seguinte,
esse projecto usa uma JSON API(fake api) que eu fiz ela e hospedei no heroku,  e a url da api tem que ser informada nas variáveis de ambiente, eu esqueci de colocar o .env-example , o projecto da api é [este](https://github.com/isaiasnhantumbo/worldtrip-server), e o nome da variável de ambiente é **NEXT_PUBLIC_API_URL**.
Creio que com isso consiga rodar o projecto com sucesso
